### ISSUE TITLE
Unable to make anything appear

### ISSUE THREAD

**Issue by Geldahar** [erversteeg/Xp-Goals#1]
Ive tried messing with the configuration settings for multiple skills but i cant seem to get anything to pop up onto the screen. Not sure if maybe im doing something wrong.

**Comment by Geldahar** [comment]
I figured out the problem. Unchecking the days of the week caused it to appear.

**Comment by iGundamStyle** [comment]
Having same issue

**Comment by erversteeg** [comment]
Sorry missed this. Should be fixed at this point.
