### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by BaldySailor** [erversteeg/Xp-Goals#2]
Have the option to automatically hide bars when goal has been met, and for it to appear when it resets again.

Have the option to stack the bars horizontally or vertically x times and a new stack starts. I have them stacked on the bottom of the screen so they are visible but not blocking much of the screen.

**Comment by erversteeg** [comment]
Great suggestions. I will get these added in.

**Comment by erversteeg** [comment]
These changes are live as of today.
