### ISSUE TITLE
Custom Time for daily goals

### ISSUE THREAD

**Issue by Rough-Draft** [erversteeg/Xp-Goals#3]
I get off work late at night just before midnight, I then stay up late gaming until the early hours of the morning when I got to sleep in prep for work. I would like to set daily xp goals that start and end at say 10pm. So I guess my suggestion is way to make a custom goal that resets daily but overlaps midnight.

Thanks.

**Comment by erversteeg** [comment]
Great suggestion. I will get this added in.

**Comment by erversteeg** [comment]
Added a reset offset so you can specify -2 hours and it will reset your daily goals at 10pm. The update is pending on Plugin Hub and can take anywhere from one day to a few weeks to go live in the game.

**Comment by Rough-Draft** [comment]
> Added a reset offset so you can specify -2 hours and it will reset your daily goals at 10pm. The update is pending on Plugin Hub and can take anywhere from one day to a few weeks to go live in the game.

Woah, that was fast! Tysm

**Comment by erversteeg** [comment]
Sure thing, the update now live in the game. Thanks again for the great suggestion.
