### ISSUE TITLE
Offset day enabledness with 'Reset Offset'

### ISSUE THREAD

**Issue by KaiseerKenopsia** [erversteeg/Xp-Goals#4]
I'd like to have untill 4am to finish my goals, so I put an 4h offset reset in the settings, but with midnight, the skills change to the next day ones. If I have a skill enabled in both days it resets correctly at 4am. 
Would it be possible to either offset "day enabledness" with 'Reset Offset' setting, or make another offset setting for the day enabler check-boxes?

**Comment by erversteeg** [comment]
Yeah I think what can fix that is to have a checkbox that will align skill visibility settings with the reset offset. I'll get working on it.

**Comment by erversteeg** [comment]
Ok so there's now two checkboxes one for offsetting reset times and another for offsetting track patterns so if both the skill reset and track patterns boxes are checked it will offset days of the week by the same amount as the reset.
