### ISSUE TITLE
Add setting for 'max displayed goals'

### ISSUE THREAD

**Issue by KaiseerKenopsia** [erversteeg/Xp-Goals#5]
I'd love it if I could set a 'maximum number of displayed goal bars'.

I'm using the plugin to help me keep myself motivated by setting a lot of different small goals that usually reset weekly or daily, depending on the skill. 
With about 6 daily goals set and a few weekly ones that I set manually it often starts to take up a lot of space.
 
I made the bars smaller etc. Still, too many visible goals can get me unfocused sometimes, so the option to set max visible goals would help a lot :)

-----------
Also, if you'll be adding this, it would be nice if you considered adding a setting for how to sort the goals to top.
 
By 'percentage done' is nice, I think that's what you're using now. Some more useful ones IMO would be by 'XP left to goal' and by 'XP gained' and the option to reverse these.

**Comment by erversteeg** [comment]
These are awesome. I got both added in today and they are pending approval. Sometimes can take up to a few weeks but is usually faster.

**Comment by erversteeg** [comment]
Got both these added.
